- src/App.js
- src/Pages/Meeting/Board.css
- src/Pages/Meeting/Board.js
> Design 모임 게시글 페이지

- src/App.js
- src/Css/Home/Home.css
- src/Css/Meeting/MyPosts.css
- src/Css/Member/Login.css
- src/Css/Member/MyPage.css
- src/Css/Member/SignUp.css
- src/Css/Shoppingbasket/Nav.css
- src/Js/Meeting/Board.js
- src/Js/Meeting/MyPosts.js
- src/Js/Member/Login.js
- src/Js/Member/MyPage.js
- src/Js/Member/SignUp.js
- src/Js/Restaurant/Check.js
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/Main.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
- src/components/Nav.js
> Design 중복 css 수정

- public/index.html
- src/App.js
- src/Css/Shoppingbasket/BasketView.css
- src/Css/Shoppingbasket/MenuDetail.css
- src/Css/Shoppingbasket/MenuView.css
- src/Css/Shoppingbasket/Nav.css
- src/Js/Member/Login.js
- src/Js/Member/MyPage.js
- src/Js/Member/SignUp.js
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/Basket.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
- src/Service/ApiService.js
- src/components/Nav.js
> 로그인, 회원가입, 로그아웃, 회원탈퇴 기능 추가

- src/App.js
- src/Css/Shoppingbasket/BasketView.css
- src/Css/Shoppingbasket/MenuDetail.css
- src/Css/Shoppingbasket/MenuView.css
- src/Css/Shoppingbasket/Nav.css
- src/Js/Member/Login.js
- src/Js/Member/MyPage.js
- src/Js/Member/SignUp.js
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/Basket.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
- src/Service/ApiService.js
- src/components/Nav.js
로그인, 회원가입, 로그아웃, 회원탈퇴 기능 추가 &Basket.js 파일 추가 & css 정리
> 로그인, 회원가입, 로그아웃, 회원탈퇴 기능 추가 &Basket.js 파일 추가 & css 정리

- public/index.html
- src/App.js
- src/Js/Meeting/MakeMap.js
- src/Js/Member/SignUp.js
- src/Js/Shoppingbasket/Basket.js
- src/Js/Shoppingbasket/BasketView_notList.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Service/ApiService.js
- src/Service/app-config.js
- src/components/KakaoMap.js
[장바구니 연동 준비(BasketView_notList.js - 임시 파일) & 지도에 경도 위도를 이용하여 주소 띄우기]
[KakaoMap > MakeMap 파일 이름 변경 & Meeting 폴더로 이동]
> 장바구니 연동 준비(BasketView_notList.js - 임시 파일) & 지도에 경도 위도를 이용하여 주소 띄우기

- src/App.js
- src/Css/Home/Home.css
- src/Css/Meeting/Board.css
- src/Css/Meeting/Make.css
- src/Css/Restaurant/Check.css
- src/Js/Home/Home.js
- src/Js/Meeting/Board.js
- src/Js/Meeting/Make.js
- src/Js/Restaurant/Check.js
> Feat 백엔드 연동 

- src/Css/Meeting/MyPosts.css
- src/Css/Member/MyPage.css
- src/Js/Meeting/MyPosts.js
- src/Js/Member/MyPage.js
> Design 디자인 중복 수정

- src/App.js
- src/Js/Member/MyPage.js
- src/Js/Member/SignUp.js
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
- src/Service/app-config.js
Board.js 에서 Menuview.js로 boardNo 전달받는 부분 연결
> Board.js 에서 Menuview.js로 boardNo 전달받는 부분 연결

- src/App.js
- src/Js/Meeting/MyPosts.js
- src/Js/Member/MyPage.js
- src/Js/Member/SignUp.js
회원가입 push 이메일 추가 & 마이페이지 수정 & 회원탈퇴 오류 수정
> 회원가입 push 이메일 추가 & 마이페이지 수정 & 회원탈퇴 오류 수정

- src/Js/Meeting/MakeMap.js
MakeMap.js 에서 모임 게시물 생성 페이지에 일부 데이터만 들어가는 이슈 해결 및 주소 데이터 가져오도록 했습니다.
> Fix 모임 게시물 생성 페이지에서 일부 데이터만 들어가는 이슈 및 주소 데이터 가져오기

- src/Js/Home/Home.js
- src/Js/Meeting/Make.js
MakeMap.js 파일에서 DB의 컬럼명과 통일하였습니다.
> Fix DB의 컬럼명과 통일

- src/Css/Home/Home.css
- src/Css/Meeting/Make.css
- src/Js/Meeting/Board.js
- src/Js/Meeting/Make.js
- src/Js/Restaurant/Check.js
모임 게시글 생성 페이지 카테고리 선택란 삭제 및 DB의 컬럼명과 통일하였습니다. 추가로 디자인 변경하였습니다.
> Feat 모임 게시글 생성 페이지 카테고리 선택란 삭제 및 DB의 컬럼명과 통일

- src/Js/Meeting/MakeMap.js
> Design Map 디자인 수정

- src/Js/Shoppingbasket/BasketView.js
- src/Service/ApiService.js
- src/Service/app-config.js
장바구니 주문 취소 버튼 수정 & 로그인 시 home으로 가도록 경로 수정
> 장바구니 주문 취소 버튼 수정 & 로그인 시 home으로 가도록 경로 수정

- src/Css/Meeting/Make.css
- src/Js/Meeting/Make.js
- src/Js/Restaurant/Check.js
모임 게시글 생성 페이지 상세주소 입력란 추가 및 디자인 수정했습니다.
> Feat 모임 게시글 생성 페이지 상세주소 입력란 추가 및 디자인 수정

- src/Js/Meeting/MakeMap.js
> Feat 모임 게시글 생성 페이지 수정에 따른 맵 페이지 수정

- src/Css/Home/Home.css
- src/Css/Meeting/Board.css
- src/Css/Meeting/Make.css
- src/Css/Restaurant/Check.css
- src/Js/Home/Home.js
- src/Js/Meeting/Board.js
- src/Js/Meeting/Make.js
- src/Js/Restaurant/Check.js
모임 게시글 삭제 기능을 추가하고 생성 시 최대 인원 수 저장 및 음식점과 위치 선택 후 디자인을 변경하였습니다. 또한 주요 색상 전부 변경했습니다.
> Feat 모임 게시글 기능

- src/Css/Home/Home.css
- src/Css/Meeting/Make.css
- src/Css/Restaurant/Check.css
- src/Js/Home/Home.js
- src/Js/Meeting/Board.js
- src/Js/Meeting/Make.js
모임 게시글 상세페이지 및 생성페이지 오류 수정했습니다.
> Fix 모임 게시글 상세페이지 및 생성페이지 오류 수정

- package-lock.json
- package.json
- src/Css/Meeting/MyPosts.css
- src/Css/Member/Login.css
- src/Css/Member/MyPage.css
- src/Css/Member/SignUp.css
- src/Css/Member/Update.css
- src/Css/Shoppingbasket/Nav.css
- src/Js/Meeting/MyPosts.js
- src/Js/Member/Login.js
- src/Js/Member/MyPage.js
- src/Js/Member/SignUp.js
- src/Js/Member/Update.js
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
- src/Service/app-config.js
- src/components/Nav.js
장바구니 full name 보이게 수정 & 회원관리 (회원탈퇴 관련 오류 제외)
> 장바구니 full name 보이게 수정 & 회원관리 (회원탈퇴 관련 오류 제외)

- src/Css/Shoppingbasket/BasketView.css
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/BasketView.js
> 장바구니 css 추가수정

- src/Js/Home/Home.js
- src/Js/Meeting/Board.js
- src/Service/ApiService.js
> Feat 에러 처리

- src/Js/Home/Home.js
- src/Js/Meeting/Make.js
- src/Service/ApiService.js
> Feat 에러 추가 처리

- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/Basket.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
- src/components/Nav.js
Nav bar 고정된 페이지로 뒤로 가도록 수정 & 코드 정리
> Nav bar 고정된 페이지로 뒤로 가도록 수정 & 코드 정리

- src/Css/Shoppingbasket/BasketView.css
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/Basket.js
- src/Js/Shoppingbasket/BasketView.js
> 에러 처리 css 수정 (장바구니가 없습니다.)

- src/Css/Home/Home.css
- src/Css/Meeting/MyPosts.css
- src/Css/Member/MyPage.css
- src/Css/Member/Update.css
- src/Css/Shoppingbasket/BasketView.css
- src/Js/Member/Update.js
- src/Js/Shoppingbasket/BascketViewHost.js
- src/Js/Shoppingbasket/BasketView.js
- src/Js/Shoppingbasket/MenuDetail.js
- src/Js/Shoppingbasket/MenuView.js
> Design 전체 디자인 수정 및 통일 2차 추가

- src/Service/ApiService.js
> Feat 에러 2차 추가 처리

- src/Js/Meeting/MyPosts.js
- src/Js/Shoppingbasket/BasketView.js
MyPosts.js 내가 참여한 게시물 api 호출 오류 수정 & 장바구니 조회(일반) css 수정
> MyPosts.js 내가 참여한 게시물 api 호출 오류 수정 & 장바구니 조회(일반) css 수정

- public/index.html
- src/Js/Member/SignUp.js
- src/Js/Restaurant/Check.js
- src/Service/ApiService.js
앱 화면에 돋보기 보이는 문제 해결 & 회원가입 페이지 오류 수정 & call 함수 return 오류 수정 & 이미지 보이게 성공
> 앱 화면에 돋보기 보이는 문제 해결 & 회원가입 페이지 오류 수정 & call 함수 return 오류 수정 & 이미지 보이게 성공

- src/Css/Meeting/MyPosts.css
- src/Css/Member/Login.css
- src/Css/Member/MyPage.css
- src/Css/Member/SignUp.css
- src/Css/Member/Update.css
> 회원관리 페이지 css 기기에 맞게 수정

- src/Css/Home/Home.css
- src/Css/Meeting/Board.css
- src/Css/Meeting/Make.css
- src/Css/Meeting/MyPosts.css
- src/Css/Member/Login.css
- src/Css/Member/MyPage.css
- src/Css/Member/SignUp.css
- src/Css/Member/Update.css
- src/Css/Shoppingbasket/BasketView.css
- src/Css/Shoppingbasket/MenuView.css
- src/Css/Shoppingbasket/Nav.css
- src/Js/Meeting/Board.js
- src/Js/Meeting/Make.js
- src/Js/Meeting/MyPosts.js
- src/Js/Member/Update.js
- src/Service/ApiService.js
> Design 헤더 고정 디자인 수정
